### PR TITLE
Contact us form

### PR DESCRIPTION
**Pull request by meghanakn473**
I have added the contact us form in the contact section, also ensured the validation to it to avoid faulty messages.

Screenshot (182)
Screenshot (183)

@Sanskriti1102 please review and allow merge and assign labels level 2, gssoc-extd, hacktoberfest

### CODE REVIEW

**Comment by meghanakn473** [comment]
@Sanskriti1102 @Krishi1211 please review and allow merge and assign the labels level 2, gssoc-ext, hacktoberfest

**Comment by Krishi1211** [comment]
@meghanakn473 have you connected it with the backend?

**Comment by meghanakn473** [comment]
I'll update by eod @Krishi1211

**Comment by meghanakn473** [comment]
> @meghanakn473 have you connected it with the backend?

What exactly u meant? If u could explain @Krishi1211

**Comment by meghanakn473** [comment]
@Sanskriti1102 @Krishi1211 i have made all the changes and applied as per my issue, kindly review and allow merge
yes i hv connected to backend

**Comment by Krishi1211** [comment]
https://docs.google.com/spreadsheets/d/1r60v-ydSCpLIq6Ub3jfzWiFwDWvtHR0qsQmo3CM7rPQ/edit?usp=sharing

@meghanakn473 refer this sheet for input values

**Comment by Sanskriti1102** [comment]
@meghanakn473 can u change the theme of the contact form ?

**Comment by meghanakn473** [comment]
hey @Krishi1211  @Sanskriti1102 please allow merge to my pr made

**Pull request merged**
