### PR TITLE
Added the logo

### PR DESCRIPTION
**Pull request by Slambot01**
I have added the logo as it was task assigned to me.I am adding images for your reference.

before:
image

after:
image

### CODE REVIEW

**Comment by Sanskriti1102** [comment]
@Slambot01 the logo height isn't proper, do review it asap

**Comment by Slambot01** [comment]
Do you want me to increase the size?

**Comment by Slambot01** [comment]
@Sanskriti1102  please check it once

image

**Comment by Sanskriti1102** [comment]
@Slambot01 resize it a bit more, it's looking compressed a bit !

**Comment by Slambot01** [comment]
@Sanskriti1102  done.In order to maintain the height to width ratio this time ,I've taken  the help of canva while setting the dimensions of logo.Do i have to create a new PR for the updated code ?

image

**Pull request merged**
