### PR TITLE
Add dark and light mode icons and update styles (issue #62) 

### PR DESCRIPTION
**Pull request by coder-writes**
hey @Sanskriti1102 , This Pull Regarding the issue #62 which is to change between the dark and light mode of the website.
This pull request includes significant changes to the `css/style.css` and `index.html` files aimed at improving the theme toggle functionality and cleaning up the styling. The most important changes include adding a theme toggle button, modifying the hover styles, and commenting out unnecessary color definitions.

### Theme Toggle Functionality:

* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R21-R44): Added JavaScript functions `lightMode`, `darkMode`, and `mode` to handle theme switching. Introduced a button with an `onclick` event to toggle between light and dark modes. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R21-R44) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R354-R371)

### Styling Adjustments:

* [`css/style.css`](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R322-R330): Added styles for the new theme toggle button. (`#theme-toggle` selector)
* [`css/style.css`](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R370): Replaced `-webkit-appearance` with `appearance` for better cross-browser compatibility. [[1]](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R370) [[2]](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R400) [[3]](diffhunk://#diff-

### Minor HTML Adjustments:

* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L73-R97): Removed inline color styles from various elements to allow for dynamic theme changes. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L73-R97) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L110-R134) [[3]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R167-R171) [[4]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L171-R196) [[5]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L252-R280) [[6]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L282-R309) [[7]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L298-R329) [[8]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L476-R507) [[9]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L505-R536) [[10]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L516-R547) [[11]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L541-R572)

These changes collectively enhance the website's maintainability and user experience by introducing a theme toggle and cleaning up the CSS.
### Theme Toggle Feature:
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R21-R44): Added JavaScript functions `lightMode`, `darkMode`, and `mode` to switch between light and dark themes. Added a button to toggle themes. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R21-R44) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R354-R371)

### Minor Styling Adjustments:
* [`css/style.css`](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R84): Added hover color change for `.invite-button` to ensure text color changes on hover.
* [`css/style.css`](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R370): Added `appearance` property to various input types for consistency across browsers. [[1]](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R370) [[2]](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R400) [[3]](diffhunk://#diff-1fc556f95754ee7e33d91044125c44bb9f750c99be4406756ffb27413adfcaf5R439)

### HTML Adjustments:
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L73-R97): Commented out inline color styles to clean up the HTML and make it more maintainable. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L73-R97) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L110-R134) [[3]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R167-R171) [[4]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L171-R196) [[5]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L252-R280) [[6]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L282-R309) [[7]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L298-R329)
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L476-R507): Removed inline color styles from buttons to allow CSS to handle styling. [[1]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L476-R507) [[2]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L505-R536) [[3]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L516-R547) [[4]](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L541-R572)Added new SVG icons for dark and light mode. Also made some updates to the styles in the SCSS and CSS files.

@Sanskriti1102 @Krishi1211 Please have a look at the Changes and let me know if needed any further changes and improvements , and if not please merge this pr under the tag Gssoc Extd and Hacktoberfest and level 3 as it had taken a lot of efforts.

### CODE REVIEW

**Comment by Krishi1211** [comment]
@coder-writes Can You share the demo video

**Comment by coder-writes** [comment]
https://drive.google.com/uc?id=1Gv47R-_FIk7-cNujAlFpYD84XVSVAd_3&export=download 
@Krishi1211  this is the video link of drive , please let me know if you can not be able to access the video.

**Comment by coder-writes** [comment]
> Please share the access to video

https://drive.google.com/file/d/1Gv47R-_FIk7-cNujAlFpYD84XVSVAd_3/view?usp=sharing

This the public link for the video.

**Comment by Krishi1211** [comment]
@coder-writes please remove the hover feature on "We feature Icon Section"

**Comment by coder-writes** [comment]
@Krishi1211 @Sanskriti1102 Please have a look at the changes regarding the removing the hover effect from the we Feature on section.

**Comment by coder-writes** [comment]
hey @Krishi1211 @Sanskriti1102  please respond atleast , what anything else you want , I have spend my whole 1-2 days on this to understand your messy code base and CSS  properties now you are not replying even, I know their may be some mistakes and suggestions in the pull request but at least give the response .

**Comment by Sanskriti1102** [comment]
@coder-writes we were tending to other issues as well, meanwhile if this got skipped then it's an apology from our side. We will review and let you know asap !

**Comment by Sanskriti1102** [comment]
@coder-writes can u send us the video of the changes made? since the preview is showing the same unchanged one

**Pull request closed without merging**
