### PR TITLE
added email and google sheets functionality issue #65

### PR DESCRIPTION
**Pull request by AyushSharma72**
what is did :

1) I set up backend in nodejs

2) i added an Api which sends data to google sheets and your email

demo data send form postman to test api:
image

email received by the user:
WhatsApp Image 2024-10-12 at 22 39 51_1fe4056a

data insert in google sheets:
image

**please add gssoc-ext and level3 labels before merge**

### CODE REVIEW

**Comment by Krishi1211** [comment]
@AyushSharma72 can we store the data in https://docs.google.com/spreadsheets/d/1r60v-ydSCpLIq6Ub3jfzWiFwDWvtHR0qsQmo3CM7rPQ/edit?usp=drivesdk?

**Comment by AyushSharma72** [comment]
> @AyushSharma72 can we store the data in https://docs.google.com/spreadsheets/d/1r60v-ydSCpLIq6Ub3jfzWiFwDWvtHR0qsQmo3CM7rPQ/edit?usp=drivesdk?

yes i will edit the code for your sheet but give me edit access for demo purpose
you ahve to give edit access to  this 

ayush-49@auth-5e92f.iam.gserviceaccount.com

let me know when u do it and also if u cannot do it

**Comment by Krishi1211** [comment]
Done @AyushSharma72

**Comment by AyushSharma72** [comment]
> Done @AyushSharma72

wait let me do it now and make a PR

**Comment by AyushSharma72** [comment]
> Done @AyushSharma72

done @Krishi1211 
image

**Pull request merged**
