### PR TITLE
issue #29 Podcast Invitation Modal and Button Feature

### PR DESCRIPTION
**Pull request by meghanakn473**
This feature adds a Podcast Invitation modal to the top right corner of the application. Users can click the "Join the Podcast" button to open a modal with details about the Tech Talks X IntelligenZ's podcast and a link to a Google Form for registration. This enhancement promotes user engagement and encourages community involvement in our podcast initiatives.

https://github.com/user-attachments/assets/87bacfe0-f5b5-402a-a41d-dac8de0b2530

### CODE REVIEW

**Comment by meghanakn473** [comment]
@Sanskriti1102 please review and merge

**Comment by meghanakn473** [comment]
> @Sanskriti1102 please review and merge

also please assign the labels

**Comment by Sanskriti1102** [comment]
@meghanakn22 just change the colour of the button as per the colour code given in the read me file, put a hover effect on that button

**Comment by meghanakn473** [comment]
> @meghanakn22 just change the colour of the button as per the colour code given in the read me file, put a hover effect on that button

Done !!

**Comment by Sanskriti1102** [comment]
@meghanakn473 check the colour code in the read me and according to that try to make the button !

**Comment by meghanakn473** [comment]
> @meghanakn473 check the colour code in the read me and according to that try to make the button !

i changed it to blue, it was give in readme......correct me if im wrong

**Comment by Sanskriti1102** [comment]
@meghanakn473 i can't see the changes in the preview, can u send me it's link ?

**Comment by meghanakn473** [comment]
> @meghanakn473 i can't see the changes in the preview, can u send me it's link ?

http://localhost:3000/

Screenshot (149)

**Comment by Sanskriti1102** [comment]
@meghanakn473 can u make the button look a bit gradient like it's done in 
AI's next frontier one?

**Comment by meghanakn473** [comment]
> @meghanakn473 can u make the button look a bit gradient like it's done in AI's next frontier one?

Screenshot (150)

is this fine??

**Comment by Sanskriti1102** [comment]
@meghanakn473 or else do one thing, 
Change the text into white and keep the rectangle invisible i.e black and when we hover on it it should get underlined with blue and the text changing to blue just like when u hover on the "Home" ...

**Comment by meghanakn473** [comment]
> @meghanakn473 or else do one thing, Change the text into white and keep the rectangle invisible i.e black and when we hover on it it should get underlined with blue and the text changing to blue just like when u hover on the "Home" ...


https://github.com/user-attachments/assets/b1975519-ce71-475d-943b-dc2c4c7758ea

i think this must really be fine!! please approve and merge...

**Comment by meghanakn473** [comment]
@Sanskriti1102 ??

**Comment by meghanakn473** [comment]
@Sanskriti1102 please check and merge it

**Comment by Sanskriti1102** [comment]
@meghanakn473 let me review once

**Comment by Sanskriti1102** [comment]
@meghanakn473 approved

**Pull request merged**
