### PR TITLE
Created The FAQ page

### PR DESCRIPTION
**Pull request by Mandy1200**
My issue number #56 

Created the FAQ page , with matching theme and subsequent amount of quetions 

Snippet of the page
Screenshot (111)

### CODE REVIEW

**Comment by Mandy1200** [comment]
Ok , Sure

**Comment by Sanskriti1102** [comment]
@Mandy1200 can u send me a ss of the same to verify ?

**Comment by Mandy1200** [comment]
image

is this okay

**Comment by Krishi1211** [comment]
merged

**Pull request merged**
