### PR TITLE
Update Twitter icon in index.html

### PR DESCRIPTION
**Pull request by Amanjayswal500**
Update Twitter's old icon to the current icon "X" in index.html
Screenshot 2024-10-06 154736

### CODE REVIEW

**Comment by Krishi1211** [comment]
Can you also update it in "We feature on" Section

**Comment by Sanskriti1102** [comment]
@Amanjayswal500 the logo X for twitter is invisible, do update it also our mentor @Krishi1211 has commented above do mention that as well!

**Comment by Sanskriti1102** [comment]
image
here the logo isn't visible, recheck the code @Amanjayswal500

**Comment by Krishi1211** [comment]
resolved

**Pull request closed without merging**
