### PR TITLE
Added a auto scrollable responsive testimonial section

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #119 

https://github.com/user-attachments/assets/08d9de56-7079-4ee2-ad9d-697b894b687e

image

Mobile screen !!

### CODE REVIEW

**Comment by Sawan-Kushwah** [comment]
@Sanskriti1102 why it doesn't get merge is there any problem ?

**Comment by Sanskriti1102** [comment]
image
@Sawan-Kushwah pls resolve it

**Comment by Sawan-Kushwah** [comment]
@Sanskriti1102 done resolving all conflicts!!

**Comment by Sawan-Kushwah** [comment]
@Sanskriti1102 i have resolved conflicts

**Pull request merged**
