### PR TITLE
Well aligned stats section with animation

### LINKED ISSUE #85: Enhance the 'stats' section in the website
1)   I would like to add a dynamic counting animation for the numbers in the below shown section, starting from 0 and counting up to their final values over a few seconds. This would enhance the user interaction.

2)  Also I would like to well align it properly, since it is not well aligned.

Capturedfjrnf

@Sanskriti1102  Kindly assign me this issue under the gssoc and hacktoberfest labels.

### PR DESCRIPTION
**Pull request by swathivemula7**
Closes #85 

I have well aligned the stats section and also added a slight animation of the cards on hover.

https://github.com/user-attachments/assets/06a7891f-2c03-4260-9390-77283cafa3e9

@Krishi1211 Kindly review at the earliest.

### CODE REVIEW

**Comment by Sanskriti1102** [comment]
@swathivemula7 please review our youtube channel : https://www.youtube.com/channel/UCbUtPTIsWVP5AhbswlpKqww 
and update the stats accordingly

**Comment by swathivemula7** [comment]
@Sanskriti1102 I have added the correct stats now along with plus icon near the number


https://github.com/user-attachments/assets/736dfbda-5883-47a9-8e1d-85f18686f9d2

**Comment by swathivemula7** [comment]
@Sanskriti1102 I have added correct stats along with plus icon near the numbers.


https://github.com/user-attachments/assets/552a2e3f-e93d-4d16-a6e9-e5d7767726d4

**Comment by swathivemula7** [comment]
@Sanskriti1102 I have made the required changes...kindly review the updated PR.

**Comment by Krishi1211** [comment]
@swathivemula7  merged

**Pull request merged**
